import type { Metadata } from "next";
import { Jersey_20, Bitcount_Grid_Single } from "next/font/google";
import "./globals.css";

const jersey20 = Jersey_20({
  variable: "--font-jersey",
  subsets: ["latin"],
  weight: "400",
});

const bitcount = Bitcount_Grid_Single({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bitcount.variable} ${jersey20.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
